// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzWMGavdE5tzZf15Nxl--w92o9G44KW48',
    appId: '1:341023915082:web:4661b8755081a07cc33ab3',
    messagingSenderId: '341023915082',
    projectId: 'my-immoble-app',
    authDomain: 'my-immoble-app.firebaseapp.com',
    storageBucket: 'my-immoble-app.appspot.com',
    measurementId: 'G-EEQJG0ZEK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpKuPHfMfbk5UV6YCfr6Q6wUFRioz7xh4',
    appId: '1:341023915082:android:2b567be8c3848da2c33ab3',
    messagingSenderId: '341023915082',
    projectId: 'my-immoble-app',
    storageBucket: 'my-immoble-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfD_hSNwQiNN16Gp9d6H8R4tlgxBRntYM',
    appId: '1:341023915082:ios:3800c31326600e8fc33ab3',
    messagingSenderId: '341023915082',
    projectId: 'my-immoble-app',
    storageBucket: 'my-immoble-app.appspot.com',
    iosBundleId: 'com.example.acheUmLar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfD_hSNwQiNN16Gp9d6H8R4tlgxBRntYM',
    appId: '1:341023915082:ios:7843690b2c774681c33ab3',
    messagingSenderId: '341023915082',
    projectId: 'my-immoble-app',
    storageBucket: 'my-immoble-app.appspot.com',
    iosBundleId: 'com.example.acheUmLar.RunnerTests',
  );
}
